name: First-Actions-Job

on: push

jobs:
  TestKnowledge:
     name: learn
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: welcome message
       run: echo "welcome to my first project"
     - name: see the files
       run: ls -al
     - name: view the contents of file
       run: cat "README.md"


