name: First-Actions-Job

on: push

jobs:
   create-file:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: create file
        run: |
           sudo apt update -y 
           sudo apt install cowsay -y
           cowsay -f dragon "I am king of fire am dragon" >> dragon.txt

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
           name: dragon-file
           path: dragon.txt

   check-file:
       needs: create-file
       runs-on: ubuntu-latest
       steps:
       - name: download artifact
         uses: actions/download-artifact@v4
         with:
           name: dragon-file
       - name: ckeckfile
         run: grep -i "dragon" dragon.txt

   list-file:
        needs: [check-file]
        runs-on: ubuntu-latest
        steps:
        - name: download-artifact
          uses: actions/download-artifact@v4
          with:
             name: dragon-file
        - name: check-content
          run: cat dragon.txt
          
      

