name: First-Actions-Job

on: push

jobs:
  TestKnowledge:
     name: learn
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: welcome message
       run: |
          echo "welcome to my first job"
          ls -ltra
          cat README.md
    #  - name: run ascii command
    #    run: cowsay -f tiger "I am the king of the jungle" >> cowsay.txt  


